podTemplate(label: 'canary', 
  containers: [
    containerTemplate(name: 'maven-chrome', image: 'maven:3.6.3-jdk-11', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'selenium-hub', image: 'selenium/hub:4.0.0'),
    containerTemplate(name: 'selenium-chrome', image: 'selenium/node-chrome:4.0.0', envVars: [
      envVar(key: 'SE_EVENT_BUS_HOST', value: 'localhost'),
      envVar(key: 'SE_EVENT_BUS_PUBLISH_PORT', value: '4442'),
      envVar(key: 'SE_EVENT_BUS_SUBSCRIBE_PORT', value: '4443'),
      envVar(key: 'DISPLAY', value: ':99.0'),
      envVar(key: 'SE_OPTS', value: '--port 5556')
    ]),
    containerTemplate(name: 'kubectl', image: 'skyglass/kubectl:1.20.2', ttyEnabled: true, command: 'cat')
  ],
  envVars: [
    secretEnvVar(key: 'DOCKERHUB_USERNAME', secretName: 'dockerhub-username-secret', secretKey: 'USERNAME')
  ],
  volumes: [
    secretVolume(mountPath: '/etc/maven/', secretName: 'maven-settings-secret')
  ])
{
  node ('canary') {
    def image_name = "notepad"

    checkout scm

    stage('Deploy canary') {
      container('kubectl') {
        sh """
          sed -i "s/NOTEPAD_CONTAINER_IMAGE/${DOCKERHUB_USERNAME}\\/${image_name}:${CANARY_VERSION}/" ./notepad/k8s/canary/notepad-canary-deployment.yaml

          kubectl apply -f notepad/k8s/canary
          kubectl rollout status deployment notepad-deployment-canary

          kubectl get service notepad-service-canary
          kubectl get endpoints notepad-service-canary
        """
      }
    }

    dir('app') {
      stage('Checkout the Notepad application') {
        git url: 'https://github.com/skyglass/notepad.git', branch: 'master'
      }

      stage('Run Smoke Tests on Chrome') {
        container('maven-chrome') {
          sh """
            mvn -B -s /etc/maven/settings.xml clean verify -Psmoke-tests -Dacceptance.notepad.url="http://notepad-service-canary:8080" -Dselenium.browser=chrome -Dsurefire.rerunFailingTestsCount=3
          """
        }
      }
    }

    stage('Add env=production label') {
      container('kubectl') {
        sh """
          kubectl label pods -l track=canary env=production
          sleep 10

          kubectl get service notepad-service-production
          kubectl get endpoints notepad-service-production
        """
      }
    }
  }
}
