podTemplate(label: 'acceptance', 
  containers: [
    containerTemplate(name: 'maven-firefox', image: 'maven:3.6.3-jdk-11', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'maven-chrome', image: 'maven:3.6.3-jdk-11', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'selenium-hub', image: 'selenium/hub:4.0.0'),
    containerTemplate(name: 'selenium-chrome', image: 'selenium/node-chrome:4.0.0', envVars: [
      envVar(key: 'SE_EVENT_BUS_HOST', value: 'selenium-hub'),
      envVar(key: 'SE_EVENT_BUS_PUBLISH_PORT', value: '4442'),
      envVar(key: 'SE_EVENT_BUS_SUBSCRIBE_PORT', value: '4443')
    ]),
    containerTemplate(name: 'selenium-firefox', image: 'selenium/node-firefox:4.0.0', envVars: [
      envVar(key: 'SE_EVENT_BUS_HOST', value: 'selenium-hub'),
      envVar(key: 'SE_EVENT_BUS_PUBLISH_PORT', value: '4442'),
      envVar(key: 'SE_EVENT_BUS_SUBSCRIBE_PORT', value: '4443')
    ])
  ],
  volumes: [
    secretVolume(mountPath: '/etc/maven/', secretName: 'maven-settings-secret')
  ])
{
  node ('acceptance') {

    stage('Checkout the Notepad application') {
      git url: 'https://github.com/skyglass/notepad.git', branch: "${GIT_BRANCH}"
    }

    parallel (
      firefox: {
        stage('Run Acceptance Tests on Firefox') {
          container('maven-firefox') {
            sh """
              mvn -B -s /etc/maven/settings.xml clean verify -Pacceptance-tests -Dacceptance.notepad.url=${NOTEPAD_URL} -Dselenium.browser=firefox -Dsurefire.rerunFailingTestsCount=3
            """
          }
        }
      },
      chrome: {
        stage('Run Acceptance Tests on Chrome') {
          container('maven-chrome') {
            sh """
              mvn -B -s /etc/maven/settings.xml clean verify -Pacceptance-tests -Dacceptance.notepad.url=${NOTEPAD_URL} -Dselenium.browser=chrome -Dsurefire.rerunFailingTestsCount=3
            """
          }
        }
      }
    )
  }
}
