podTemplate(label: 'acceptance',
  envVars: [
    envVar(key: 'SELENIUM_URL', value: 'http://localhost:4444/wd/hub')
  ],

yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven-firefox
    image: maven:3.6.3-jdk-11
    command: ['sleep']
    args: ['9999999']
    volumeMounts:
    - name: volume-0
      mountPath: /etc/maven/
  - name: maven-chrome
    image: maven:3.6.3-jdk-11
    command: ['sleep']
    args: ['9999999']
    volumeMounts:
    - name: volume-0
      mountPath: /etc/maven/
  - name: selenium-hub
    image: selenium/hub:4.0.0
  - name: selenium-chrome
    image: selenium/node-chrome:4.0.0
    env:
      - name: SE_EVENT_BUS_HOST
        value: localhost
      - name: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - name: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
      - name: DISPLAY
        value: :99.0
      - name: SE_OPTS
        value: -port 5556
  - name: selenium-firefox
    image: selenium/node-firefox:4.0.0
    env:
      - name: SE_EVENT_BUS_HOST
        value: localhost
      - name: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - name: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
      - name: DISPLAY
        value: :98.0
      - name: SE_OPTS
        value: -port 5557
""",

  volumes: [
    secretVolume(mountPath: '/etc/maven/', secretName: 'maven-settings-secret')
  ])

{
  node ('acceptance') { 

    dir('app') {
      stage('Checkout the Notepad application') {
        git url: 'https://github.com/skyglass/notepad.git', branch: "${GIT_BRANCH}"
      }

      parallel (
        firefox: {
          stage('Run Acceptance Tests on Firefox') {
            container('maven-firefox') {
              sh """
                mvn -B -s /etc/maven/settings.xml clean verify -Pacceptance-tests -Dselenium.url=${SELENIUM_URL} -Dacceptance.notepad.url=${NOTEPAD_URL} -Dselenium.browser=firefox -Dsurefire.rerunFailingTestsCount=3
              """
            }
          }
        },
        chrome: {
          stage('Run Acceptance Tests on Chrome') {
            container('maven-chrome') {
              sh """
                mvn -B -s /etc/maven/settings.xml clean verify -Pacceptance-tests -Dselenium.url=${SELENIUM_URL} -Dacceptance.notepad.url=${NOTEPAD_URL} -Dselenium.browser=chrome -Dsurefire.rerunFailingTestsCount=3
              """
            }
          }
        }
      )
    }
  }
}
