podTemplate(label: 'acceptance',
  containers: [
    containerTemplate(name: 'kubectl', image: 'skyglass/kubectl:1.20.2', ttyEnabled: true, command: 'cat'),   
    containerTemplate(name: 'maven-firefox', image: 'maven:3.6.3-jdk-11', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'maven-chrome', image: 'maven:3.6.3-jdk-11', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, command: 'cat')  

  ],
  volumes: [
    hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),  
    secretVolume(mountPath: '/etc/maven/', secretName: 'maven-settings-secret')
  ],
  envVars: [
    secretEnvVar(key: 'DOCKERHUB_USERNAME', secretName: 'dockerhub-username-secret', secretKey: 'USERNAME'),
    envVar(key: 'SELENIUM_URL', value: 'http://localhost:31120/wd/hub')
  ])
{
  node ('acceptance') { 

   def image_name = "notepad"

    checkout scm

    stage('Start a new Selenium Testing environment') {
      container('kubectl') {
        sh """
          sed -i "s/NOTEPAD_CONTAINER_IMAGE/${DOCKERHUB_USERNAME}\\/${image_name}:${GIT_BRANCH}/" ./notepad/k8s/acceptance-test/selenium-deployment.yaml

          kubectl apply -f notepad/k8s/acceptance-test/ -l app=selenium
          kubectl rollout status deployment selenium-deployment

          kubectl get service selenium-service
          kubectl get endpoints selenium-service
        """
      }
    }

    dir('app') {
      stage('Checkout the Notepad application') {
        git url: 'https://github.com/skyglass/notepad.git', branch: "${GIT_BRANCH}"
      }

      parallel (
        firefox: {
          stage('Run Acceptance Tests on Firefox') {
            container('maven-firefox') {
              sh """
                mvn -B -s /etc/maven/settings.xml clean verify -Pacceptance-tests -Dselenium.url=${SELENIUM_URL} -Dacceptance.notepad.url=${NOTEPAD_URL} -Dselenium.browser=firefox -Dsurefire.rerunFailingTestsCount=3
              """
            }
          }
        },
        chrome: {
          stage('Run Acceptance Tests on Chrome') {
            container('maven-chrome') {
              sh """
                mvn -B -s /etc/maven/settings.xml clean verify -Pacceptance-tests -Dselenium.url=${SELENIUM_URL} -Dacceptance.notepad.url=${NOTEPAD_URL} -Dselenium.browser=chrome -Dsurefire.rerunFailingTestsCount=3
              """
            }
          }
        }
      )
    }
  }
}
