apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  labels:
    app: selenium
    env: testing
spec:
  selector:
    app: selenium
    env: testing
  ports:
  - name: "4444"  
    protocol: TCP
    port: 4444
    targetPort: 4444
    nodePort: 31110
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-service
  labels:
    app: selenium
    env: testing
spec:
  selector:
    app: selenium
    env: testing
  ports:
    - name: port1
      protocol: TCP
      port: 6900
      targetPort: 5900

---
apiVersion: v1
kind: Service
metadata:
  name: selenium-firefox-service
  labels:
    app: selenium
    env: testing
spec:
  selector:
    app: selenium
    env: testing
  ports:
    - name: port1
      protocol: TCP
      port: 6901
      targetPort: 5900      