apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  labels:
    app: selenium
    env: testing
spec:
  selector:
    app: selenium
    env: testing
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444
    name: port0
  selector:
    app: selenium
  type: NodePort
  sessionAffinity: None