apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  labels:
    app: selenium
    env: testing
spec:
  selector:
    app: selenium
    env: testing
  ports:
  - name: "4444"  
    protocol: TCP
    port: 4444
    targetPort: 4444
    nodePort: 31110
  - name: "4443"      
    protocol: TCP
    port: 4443
    targetPort: 4443
    nodePort: 31120
  - name: "4442"      
    protocol: TCP
    port: 4442
    targetPort: 4442
    nodePort: 31130
  type: NodePort