apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  labels:
    app: selenium
    env: selenium-testing
spec:
  selector:
    app: selenium
    env: selenium-testing
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444