apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  labels:
    app: selenium
    env: testing
spec:
  selector:
    app: selenium
    env: testing
  ports:
  - name: "6900"
    port: 6900
    targetPort: 5900
   - name: "6901"
    port: 6901
    targetPort: 5900
   - name: "4442"
    port: 4442
    targetPort: 4442
  - name: "4443"
    port: 4443
    targetPort: 4443
  - name: "4444"
    port: 4444
    targetPort: 4444      
status:
  loadBalancer: {}