apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-deployment
  labels:
    app: selenium
    env: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium    
  template:
    metadata:
      labels:
        app: selenium
        env: testing
    spec:
      containers:   
      - name: selenium-chrome            
        image: selenium/node-chrome:4.0.0  
        env:
        - name: SE_EVENT_BUS_HOST
          value: localhost
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        ports:
        - containerPort: 5900
        resources: {}
        volumeMounts:
        - mountPath: /dev/shm
          name: chrome-claim0
      - name: selenium-firefox          
        image: selenium/node-firefox:4.0.0     
        env:
        - name: SE_EVENT_BUS_HOST
          value: localhost
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        ports:
        - containerPort: 5900
        resources: {}
        volumeMounts:
        - mountPath: /dev/shm
          name: firefox-claim0
      - name: selenium-hub        
        image: selenium/hub:4.0.0
        ports:
        - containerPort: 4442
        - containerPort: 4443
        - containerPort: 4444
        resources: {}               
      restartPolicy: Always
      volumes:
      - name: chrome-claim0
        persistentVolumeClaim:
          claimName: chrome-claim0
      - name: firefox-claim0
        persistentVolumeClaim:
          claimName: firefox-claim0


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: selenium
    env: testing
  name: chrome-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}     


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: selenium
    env: testing
  name: firefox-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}