apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  labels:
    app: selenium
    env: testing
spec:
  selector:
    app: selenium
    env: testing
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 4444
  type: NodePort
