apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
spec:
  ports:
  - name: "6900"
    port: 6900
    targetPort: 5900
  selector:
    io.kompose.service: chrome
status:
  loadBalancer: {}
